[[permission]]
identifier = "allow-get-setting"
description = "Enables the get_setting command without any pre-configured scope."
commands.allow = ["get_setting"]
commands.deny = []

[[permission]]
identifier = "allow-set-setting"
description = "Enables the set_setting command without any pre-configured scope."
commands.allow = ["set_setting"]
commands.deny = []

[[permission]]
identifier = "allow-get-all-settings"
description = "Enables the get_all_settings command without any pre-configured scope."
commands.allow = ["get_all_settings"]
commands.deny = []
