[[permission]]
identifier = "allow-fetch-table-data"
description = "Enables the fetch_table_data command without any pre-configured scope."
commands.allow = ["fetch_table_data"]
commands.deny = []

[[permission]]
identifier = "allow-update-table-row"
description = "Enables the update_table_row command without any pre-configured scope."
commands.allow = ["update_table_row"]
commands.deny = []

[[permission]]
identifier = "allow-touch-table-data"
description = "Enables the touch_table_data command without any pre-configured scope."
commands.allow = ["touch_table_data"]
commands.deny = []

[[permission]]
identifier = "allow-evict-table-data"
description = "Enables the evict_table_data command without any pre-configured scope."
commands.allow = ["evict_table_data"]
commands.deny = []

[[permission]]
identifier = "allow-restore-table-data-cache"
description = "Enables the restore_table_data_cache command without any pre-configured scope."
commands.allow = ["restore_table_data_cache"]
commands.deny = []

[[permission]]
identifier = "allow-sync-table-data-cache-after-insert"
description = "Enables the sync_table_data_cache_after_insert command without any pre-configured scope."
commands.allow = ["sync_table_data_cache_after_insert"]
commands.deny = []

[[permission]]
identifier = "allow-sync-table-data-cache-after-update"
description = "Enables the sync_table_data_cache_after_update command without any pre-configured scope."
commands.allow = ["sync_table_data_cache_after_update"]
commands.deny = []

[[permission]]
identifier = "allow-sync-table-data-cache-after-delete"
description = "Enables the sync_table_data_cache_after_delete command without any pre-configured scope."
commands.allow = ["sync_table_data_cache_after_delete"]
commands.deny = []

[[permission]]
identifier = "allow-insert-table-row"
description = "Enables the insert_table_row command without any pre-configured scope."
commands.allow = ["insert_table_row"]
commands.deny = []

[[permission]]
identifier = "allow-delete-table-row"
description = "Enables the delete_table_row command without any pre-configured scope."
commands.allow = ["delete_table_row"]
commands.deny = []

[[permission]]
identifier = "allow-export-table-data"
description = "Enables the export_table_data command without any pre-configured scope."
commands.allow = ["export_table_data"]
commands.deny = []

[[permission]]
identifier = "allow-fetch-blob-value"
description = "Enables the fetch_blob_value command without any pre-configured scope."
commands.allow = ["fetch_blob_value"]
commands.deny = []

[[permission]]
identifier = "allow-read-file-bytes"
description = "Enables the read_file_bytes command without any pre-configured scope."
commands.allow = ["read_file_bytes"]
commands.deny = []

[[permission]]
identifier = "allow-write-file-bytes"
description = "Enables the write_file_bytes command without any pre-configured scope."
commands.allow = ["write_file_bytes"]
commands.deny = []
