/**
 * Centralised SQL keyword and built-in function lists.
 *
 * - `SQL_KEYWORDS` — uppercase SQL statement keywords used for fallback completions.
 *   These are rendered as `CompletionItemKind.Keyword` in the editor.
 * - `SQL_BUILTIN_FUNCTIONS` — uppercase MySQL/MariaDB built-in function names used
 *   for fallback completions. These are rendered as `CompletionItemKind.Function`.
 *   Sourced from the MariaDB Functions & Operators reference plus MySQL 8.4's
 *   built-in function reference to cover server-specific functions on both engines.
 * - `SQL_RESERVED_WORDS_SET` — lowercase Set used to filter out reserved words
 *   that cannot be table aliases.  Derived from SQL_KEYWORDS plus a handful of
 *   additional reserved words needed by the alias resolver.
 */

// ---------------------------------------------------------------------------
// SQL statement keywords (uppercase — used for completion items)
// ---------------------------------------------------------------------------

export const SQL_KEYWORDS: readonly string[] = [
  'SELECT',
  'FROM',
  'WHERE',
  'JOIN',
  'INNER',
  'LEFT',
  'RIGHT',
  'OUTER',
  'ON',
  'AND',
  'OR',
  'NOT',
  'IN',
  'BETWEEN',
  'LIKE',
  'IS',
  'NULL',
  'AS',
  'ORDER',
  'BY',
  'GROUP',
  'HAVING',
  'LIMIT',
  'OFFSET',
  'INSERT',
  'INTO',
  'VALUES',
  'UPDATE',
  'SET',
  'DELETE',
  'CREATE',
  'ALTER',
  'DROP',
  'TABLE',
  'INDEX',
  'VIEW',
  'DATABASE',
  'USE',
  'SHOW',
  'DESCRIBE',
  'EXPLAIN',
  'DISTINCT',
  'ALL',
  'UNION',
  'EXISTS',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'END',
  'ASC',
  'DESC',
  'PRIMARY',
  'KEY',
  'FOREIGN',
  'REFERENCES',
  'CONSTRAINT',
  'DEFAULT',
  'AUTO_INCREMENT',
  'UNIQUE',
  'WITH',
] as const

// ---------------------------------------------------------------------------
// MySQL/MariaDB built-in functions (uppercase — used for completion items)
//
// Sourced from the MariaDB Functions & Operators reference and MySQL 8.4's
// built-in function reference:
//   https://mariadb.com/docs/server/reference/sql-functions/
//   https://dev.mysql.com/doc/refman/8.4/en/built-in-function-reference.html
// Excludes: pure symbol operators, multi-word operator phrases, and
//           SYS.* schema-qualified stored functions.
// Includes: single-word operator keywords (DIV, REGEXP, RLIKE, XOR, BINARY)
//           plus MySQL/MariaDB-specific built-ins that autocomplete should know.
// ---------------------------------------------------------------------------

export const SQL_BUILTIN_FUNCTIONS: readonly string[] = [
  // --- Numeric functions ---
  'ABS',
  'ACOS',
  'ASIN',
  'ATAN',
  'ATAN2',
  'CEIL',
  'CEILING',
  'CONV',
  'COS',
  'COT',
  'CRC32',
  'CRC32C',
  'DEGREES',
  'EXP',
  'FLOOR',
  'LN',
  'LOG',
  'LOG10',
  'LOG2',
  'MOD',
  'PI',
  'POW',
  'POWER',
  'RADIANS',
  'RAND',
  'ROUND',
  'SIGN',
  'SIN',
  'SQRT',
  'TAN',
  'TRUNCATE',

  // --- String functions ---
  'ASCII',
  'BIN',
  'BINARY',
  'BIT_LENGTH',
  'CAST',
  'CHAR',
  'CHAR_LENGTH',
  'CHARACTER_LENGTH',
  'CHARSET',
  'CHR',
  'CONCAT',
  'CONCAT_WS',
  'CONVERT',
  'ELT',
  'EXPORT_SET',
  'FIELD',
  'FIND_IN_SET',
  'FORMAT',
  'FORMAT_BYTES',
  'FORMAT_PICO_TIME',
  'HEX',
  'INSERT',
  'INSTR',
  'LCASE',
  'LEFT',
  'LENGTH',
  'LOAD_FILE',
  'LOCATE',
  'LOWER',
  'LPAD',
  'LTRIM',
  'MAKE_SET',
  'MID',
  'NAME_CONST',
  'NATURAL_SORT_KEY',
  'OCT',
  'OCTET_LENGTH',
  'ORD',
  'POSITION',
  'QUOTE',
  'REPEAT',
  'REPLACE',
  'REVERSE',
  'RIGHT',
  'RPAD',
  'RTRIM',
  'SOUNDEX',
  'SPACE',
  'STRCMP',
  'SUBSTR',
  'SUBSTRING',
  'SUBSTRING_INDEX',
  'TO_BASE64',
  'FROM_BASE64',
  'TRIM',
  'UCASE',
  'UNCOMPRESS',
  'UNCOMPRESSED_LENGTH',
  'UNHEX',
  'UPPER',
  'WEIGHT_STRING',

  // --- Date/time functions ---
  'ADD_MONTHS',
  'ADDDATE',
  'ADDTIME',
  'CURDATE',
  'CURRENT_DATE',
  'CURRENT_TIME',
  'CURRENT_TIMESTAMP',
  'CURTIME',
  'DATE',
  'DATE_ADD',
  'DATE_FORMAT',
  'DATE_SUB',
  'DATEDIFF',
  'DAY',
  'DAYNAME',
  'DAYOFMONTH',
  'DAYOFWEEK',
  'DAYOFYEAR',
  'EXTRACT',
  'FROM_DAYS',
  'FROM_UNIXTIME',
  'GET_FORMAT',
  'HOUR',
  'LAST_DAY',
  'LOCALTIME',
  'LOCALTIMESTAMP',
  'MAKEDATE',
  'MAKETIME',
  'MICROSECOND',
  'MINUTE',
  'MONTH',
  'MONTHNAME',
  'NOW',
  'PERIOD_ADD',
  'PERIOD_DIFF',
  'QUARTER',
  'SEC_TO_TIME',
  'SECOND',
  'STR_TO_DATE',
  'SUBDATE',
  'SUBTIME',
  'SYSDATE',
  'TIME',
  'TIME_FORMAT',
  'TIME_TO_SEC',
  'TIMEDIFF',
  'TIMESTAMP',
  'TIMESTAMPADD',
  'TIMESTAMPDIFF',
  'TO_CHAR',
  'TO_DAYS',
  'TO_SECONDS',
  'TRUNC',
  'UNIX_TIMESTAMP',
  'UTC_DATE',
  'UTC_TIME',
  'UTC_TIMESTAMP',
  'WEEK',
  'WEEKDAY',
  'WEEKOFYEAR',
  'YEAR',
  'YEARWEEK',

  // --- Aggregate functions ---
  'AVG',
  'BIT_AND',
  'BIT_OR',
  'BIT_XOR',
  'COUNT',
  'GROUP_CONCAT',
  'JSON_ARRAYAGG',
  'JSON_OBJECTAGG',
  'MAX',
  'MEDIAN',
  'MIN',
  'STD',
  'STDDEV',
  'STDDEV_POP',
  'STDDEV_SAMP',
  'SUM',
  'VAR_POP',
  'VAR_SAMP',
  'VARIANCE',

  // --- Window functions ---
  'CUME_DIST',
  'DENSE_RANK',
  'FIRST_VALUE',
  'LAG',
  'LAST_VALUE',
  'LEAD',
  'NTH_VALUE',
  'NTILE',
  'PERCENT_RANK',
  'PERCENTILE_CONT',
  'PERCENTILE_DISC',
  'RANK',
  'ROW_NUMBER',

  // --- Control flow ---
  'COALESCE',
  'IF',
  'IFNULL',
  'NULLIF',
  'INTERVAL',

  // --- Comparison / utility functions ---
  'GREATEST',
  'ISNULL',
  'LEAST',

  // --- Information functions ---
  'BENCHMARK',
  'COERCIBILITY',
  'COLLATION',
  'CONNECTION_ID',
  'CURRENT_ROLE',
  'CURRENT_USER',
  'DATABASE',
  'DECODE_HISTOGRAM',
  'DEFAULT',
  'FOUND_ROWS',
  'LAST_INSERT_ID',
  'ROW_COUNT',
  'SCHEMA',
  'SESSION_USER',
  'SYSTEM_USER',
  'USER',
  'VERSION',

  // --- Encryption / hashing / compression ---
  'AES_DECRYPT',
  'AES_ENCRYPT',
  'COMPRESS',
  'DES_DECRYPT',
  'DES_ENCRYPT',
  'DECODE',
  'ENCODE',
  'ENCRYPT',
  'KDF',
  'MD5',
  'OLD_PASSWORD',
  'PASSWORD',
  'SHA',
  'SHA1',
  'SHA2',

  // --- JSON functions ---
  'JSON_ARRAY',
  'JSON_ARRAY_APPEND',
  'JSON_ARRAY_INSERT',
  'JSON_ARRAY_INTERSECT',
  'JSON_COMPACT',
  'JSON_CONTAINS',
  'JSON_CONTAINS_PATH',
  'JSON_DEPTH',
  'JSON_DETAILED',
  'JSON_EQUALS',
  'JSON_EXISTS',
  'JSON_EXTRACT',
  'JSON_INSERT',
  'JSON_KEY_VALUE',
  'JSON_KEYS',
  'JSON_LENGTH',
  'JSON_LOOSE',
  'JSON_MERGE',
  'JSON_MERGE_PATCH',
  'JSON_MERGE_PRESERVE',
  'JSON_NORMALIZE',
  'JSON_OBJECT',
  'JSON_OBJECT_FILTER_KEYS',
  'JSON_OBJECT_TO_ARRAY',
  'JSON_OVERLAPS',
  'JSON_PRETTY',
  'JSON_QUERY',
  'JSON_QUOTE',
  'JSON_REMOVE',
  'JSON_REPLACE',
  'JSON_SCHEMA_VALID',
  'JSON_SEARCH',
  'JSON_SET',
  'JSON_TABLE',
  'JSON_TYPE',
  'JSON_UNQUOTE',
  'JSON_VALID',
  'JSON_VALUE',

  // --- Dynamic column functions (MariaDB-specific) ---
  'COLUMN_ADD',
  'COLUMN_CHECK',
  'COLUMN_CREATE',
  'COLUMN_DELETE',
  'COLUMN_EXISTS',
  'COLUMN_GET',
  'COLUMN_JSON',
  'COLUMN_LIST',

  // --- Network / IPv6 functions ---
  'INET_ATON',
  'INET_NTOA',
  'INET6_ATON',
  'INET6_NTOA',
  'IS_IPV4',
  'IS_IPV4_COMPAT',
  'IS_IPV4_MAPPED',
  'IS_IPV6',

  // --- Lock functions ---
  'GET_LOCK',
  'IS_FREE_LOCK',
  'IS_USED_LOCK',
  'RELEASE_LOCK',

  // --- Sequence functions (MariaDB-specific) ---
  'LASTVAL',
  'NEXTVAL',
  'SETVAL',

  // --- UUID functions ---
  'SYS_GUID',
  'UUID',
  'UUID_SHORT',
  'UUIDV4',
  'UUIDV7',

  // --- Replication / GTID ---
  'BINLOG_GTID_POS',
  'MASTER_GTID_WAIT',
  'MASTER_POS_WAIT',

  // --- WSREP / Galera ---
  'WSREP_LAST_SEEN_GTID',
  'WSREP_LAST_WRITTEN_GTID',
  'WSREP_SYNC_WAIT_UPTO_GTID',

  // --- Spider engine functions ---
  'SPIDER_BG_DIRECT_SQL',
  'SPIDER_COPY_TABLES',
  'SPIDER_DIRECT_SQL',
  'SPIDER_FLUSH_TABLE_MON_CACHE',

  // --- Vector functions (MariaDB 11.6+) ---
  'VEC_DISTANCE',
  'VEC_DISTANCE_COSINE',
  'VEC_DISTANCE_EUCLIDEAN',
  'VEC_FROMTEXT',
  'VEC_TOTEXT',

  // --- XML functions ---
  'EXTRACTVALUE',
  'UPDATEXML',

  // --- Misc utility ---
  'BIT_COUNT',
  'CONVERT_TZ',
  'SLEEP',
  'TO_NUMBER',

  // --- Geometry constructors ---
  'GEOMETRYCOLLECTION',
  'LINESTRING',
  'MULTILINESTRING',
  'MULTIPOINT',
  'MULTIPOLYGON',
  'POINT',
  'POLYGON',

  // --- Geometry functions (legacy pre-ST_ aliases) ---
  'AREA',
  'ASBINARY',
  'ASTEXT',
  'ASWKB',
  'ASWKT',
  'BOUNDARY',
  'BUFFER',
  'CENTROID',
  'CONTAINS',
  'CONVEXHULL',
  'CROSSES',
  'DIMENSION',
  'DISJOINT',
  'ENDPOINT',
  'ENVELOPE',
  'EQUALS',
  'EXTERIORRING',
  'GEOMCOLLFROMTEXT',
  'GEOMCOLLFROMWKB',
  'GEOMETRYCOLLECTIONFROMTEXT',
  'GEOMETRYCOLLECTIONFROMWKB',
  'GEOMETRYFROMTEXT',
  'GEOMETRYFROMWKB',
  'GEOMETRYN',
  'GEOMETRYTYPE',
  'GEOMFROMTEXT',
  'GEOMFROMWKB',
  'GLENGTH',
  'INTERIORRINGN',
  'INTERSECTS',
  'ISCLOSED',
  'ISEMPTY',
  'ISRING',
  'ISSIMPLE',
  'LINEFROMTEXT',
  'LINEFROMWKB',
  'LINESTRINGFROMTEXT',
  'LINESTRINGFROMWKB',
  'MBRCONTAINS',
  'MBRCOVEREDBY',
  'MBRDISJOINT',
  'MBREQUAL',
  'MBREQUALS',
  'MBRINTERSECTS',
  'MBROVERLAPS',
  'MBRTOUCHES',
  'MBRWITHIN',
  'MLINEFROMTEXT',
  'MLINEFROMWKB',
  'MPOINTFROMTEXT',
  'MPOINTFROMWKB',
  'MPOLYFROMTEXT',
  'MPOLYFROMWKB',
  'MULTILINESTRINGFROMTEXT',
  'MULTILINESTRINGFROMWKB',
  'MULTIPOINTFROMTEXT',
  'MULTIPOINTFROMWKB',
  'MULTIPOLYGONFROMTEXT',
  'MULTIPOLYGONFROMWKB',
  'NUMGEOMETRIES',
  'NUMINTERIORRINGS',
  'NUMPOINTS',
  'OVERLAPS',
  'POINTFROMTEXT',
  'POINTFROMWKB',
  'POINTN',
  'POINTONSURFACE',
  'POLYFROMTEXT',
  'POLYFROMWKB',
  'POLYGONFROMTEXT',
  'POLYGONFROMWKB',
  'SRID',
  'STARTPOINT',
  'TOUCHES',
  'WITHIN',
  'X',
  'Y',

  // --- Geometry functions (ST_ namespace) ---
  'ST_AREA',
  'ST_ASBINARY',
  'ST_ASGEOJSON',
  'ST_ASTEXT',
  'ST_ASWKB',
  'ST_ASWKT',
  'ST_BOUNDARY',
  'ST_BUFFER',
  'ST_CENTROID',
  'ST_COLLECT',
  'ST_CONTAINS',
  'ST_CONVEXHULL',
  'ST_CROSSES',
  'ST_DIFFERENCE',
  'ST_DIMENSION',
  'ST_DISJOINT',
  'ST_DISTANCE',
  'ST_DISTANCE_SPHERE',
  'ST_ENDPOINT',
  'ST_ENVELOPE',
  'ST_EQUALS',
  'ST_EXTERIORRING',
  'ST_GEOHASH',
  'ST_GEOMCOLLFROMTEXT',
  'ST_GEOMCOLLFROMWKB',
  'ST_GEOMETRYCOLLECTIONFROMTEXT',
  'ST_GEOMETRYCOLLECTIONFROMWKB',
  'ST_GEOMETRYFROMTEXT',
  'ST_GEOMETRYFROMWKB',
  'ST_GEOMETRYN',
  'ST_GEOMETRYTYPE',
  'ST_GEOMFROMGEOJSON',
  'ST_GEOMFROMTEXT',
  'ST_GEOMFROMWKB',
  'ST_INTERIORRINGN',
  'ST_INTERSECTION',
  'ST_INTERSECTS',
  'ST_ISCLOSED',
  'ST_ISEMPTY',
  'ST_ISRING',
  'ST_ISSIMPLE',
  'ST_ISVALID',
  'ST_LATFROMGEOHASH',
  'ST_LENGTH',
  'ST_LINEFROMTEXT',
  'ST_LINEFROMWKB',
  'ST_LINESTRINGFROMTEXT',
  'ST_LINESTRINGFROMWKB',
  'ST_LONGFROMGEOHASH',
  'ST_MLINEFROMTEXT',
  'ST_MLINEFROMWKB',
  'ST_MPOINTFROMTEXT',
  'ST_MPOINTFROMWKB',
  'ST_MPOLYFROMTEXT',
  'ST_MPOLYFROMWKB',
  'ST_MULTILINESTRINGFROMTEXT',
  'ST_MULTILINESTRINGFROMWKB',
  'ST_MULTIPOINTFROMTEXT',
  'ST_MULTIPOINTFROMWKB',
  'ST_MULTIPOLYGONFROMTEXT',
  'ST_MULTIPOLYGONFROMWKB',
  'ST_NUMGEOMETRIES',
  'ST_NUMINTERIORRINGS',
  'ST_NUMPOINTS',
  'ST_OVERLAPS',
  'ST_POINTFROMGEOHASH',
  'ST_POINTFROMTEXT',
  'ST_POINTFROMWKB',
  'ST_POINTN',
  'ST_POINTONSURFACE',
  'ST_POLYFROMTEXT',
  'ST_POLYFROMWKB',
  'ST_POLYGONFROMTEXT',
  'ST_POLYGONFROMWKB',
  'ST_RELATE',
  'ST_SIMPLIFY',
  'ST_SRID',
  'ST_STARTPOINT',
  'ST_SYMDIFFERENCE',
  'ST_TOUCHES',
  'ST_UNION',
  'ST_VALIDATE',
  'ST_WITHIN',
  'ST_X',
  'ST_Y',

  // --- MySQL-specific built-ins not present in the MariaDB index ---
  'ANY_VALUE',
  'ASYNCHRONOUS_CONNECTION_FAILOVER_ADD_MANAGED',
  'ASYNCHRONOUS_CONNECTION_FAILOVER_ADD_SOURCE',
  'ASYNCHRONOUS_CONNECTION_FAILOVER_DELETE_MANAGED',
  'ASYNCHRONOUS_CONNECTION_FAILOVER_DELETE_SOURCE',
  'ASYNCHRONOUS_CONNECTION_FAILOVER_RESET',
  'BIN_TO_UUID',
  'GEOMCOLLECTION',
  'GROUP_REPLICATION_DISABLE_MEMBER_ACTION',
  'GROUP_REPLICATION_ENABLE_MEMBER_ACTION',
  'GROUP_REPLICATION_GET_COMMUNICATION_PROTOCOL',
  'GROUP_REPLICATION_GET_WRITE_CONCURRENCY',
  'GROUP_REPLICATION_RESET_MEMBER_ACTIONS',
  'GROUP_REPLICATION_SET_AS_PRIMARY',
  'GROUP_REPLICATION_SET_COMMUNICATION_PROTOCOL',
  'GROUP_REPLICATION_SET_WRITE_CONCURRENCY',
  'GROUP_REPLICATION_SWITCH_TO_MULTI_PRIMARY_MODE',
  'GROUP_REPLICATION_SWITCH_TO_SINGLE_PRIMARY_MODE',
  'GROUPING',
  'ICU_VERSION',
  'IS_UUID',
  'JSON_SCHEMA_VALIDATION_REPORT',
  'JSON_STORAGE_FREE',
  'JSON_STORAGE_SIZE',
  'MATCH',
  'MBRCOVERS',
  'PS_CURRENT_THREAD_ID',
  'PS_THREAD_ID',
  'RANDOM_BYTES',
  'REGEXP_INSTR',
  'REGEXP_LIKE',
  'REGEXP_REPLACE',
  'REGEXP_SUBSTR',
  'RELEASE_ALL_LOCKS',
  'ROLES_GRAPHML',
  'SOURCE_POS_WAIT',
  'ST_BUFFER_STRATEGY',
  'ST_FRECHETDISTANCE',
  'ST_GEOMCOLLFROMTXT',
  'ST_HAUSDORFFDISTANCE',
  'ST_LATITUDE',
  'ST_LINEINTERPOLATEPOINT',
  'ST_LINEINTERPOLATEPOINTS',
  'ST_LONGITUDE',
  'ST_MAKEENVELOPE',
  'ST_NUMINTERIORRING',
  'ST_POINTATDISTANCE',
  'ST_SWAPXY',
  'ST_TRANSFORM',
  'STATEMENT_DIGEST',
  'STATEMENT_DIGEST_TEXT',
  'UUID_TO_BIN',
  'VALIDATE_PASSWORD_STRENGTH',
  'VALUES',
  'WAIT_FOR_EXECUTED_GTID_SET',
] as const

// ---------------------------------------------------------------------------
// Reserved-word Set (lowercase — used by alias resolver to reject aliases
// that are actually SQL keywords)
// ---------------------------------------------------------------------------

/**
 * Additional reserved words that the alias resolver needs to reject but
 * that are not in the main SQL_KEYWORDS completion list.
 */
const EXTRA_RESERVED_WORDS: readonly string[] = [
  'cross',
  'natural',
  'using',
  'force',
  'ignore',
  'straight_join',
  'partition',
]

export const SQL_RESERVED_WORDS_SET: ReadonlySet<string> = new Set([
  ...SQL_KEYWORDS.map((k) => k.toLowerCase()),
  ...EXTRA_RESERVED_WORDS,
])
