import type { PlaywrightListColumn, PlaywrightTableDataResult } from './types'

export const BIT_TEST_LIST_COLUMNS: PlaywrightListColumn[] = [
  {
    name: 'id',
    dataType: 'int',
    nullable: false,
    columnKey: 'PRI',
    defaultValue: null,
    extra: 'auto_increment',
    ordinalPosition: 1,
  },
  {
    name: 'is_active',
    dataType: 'bit',
    nullable: false,
    columnKey: '',
    defaultValue: null,
    extra: '',
    ordinalPosition: 2,
  },
  {
    name: 'flags',
    dataType: 'bit',
    nullable: true,
    columnKey: '',
    defaultValue: null,
    extra: '',
    ordinalPosition: 3,
  },
  {
    name: 'label',
    dataType: 'varchar',
    nullable: true,
    columnKey: '',
    defaultValue: null,
    extra: '',
    ordinalPosition: 4,
  },
]

export const BIT_TEST_TABLE_DATA: PlaywrightTableDataResult = {
  columns: [
    {
      name: 'id',
      dataType: 'INT',
      isBooleanAlias: false,
      isNullable: false,
      isPrimaryKey: true,
      isUniqueKey: false,
      hasDefault: false,
      columnDefault: null,
      isBinary: false,
      isAutoIncrement: true,
    },
    {
      name: 'is_active',
      dataType: 'BIT',
      isBooleanAlias: false,
      isNullable: false,
      isPrimaryKey: false,
      isUniqueKey: false,
      hasDefault: false,
      columnDefault: null,
      isBinary: false,
      isAutoIncrement: false,
    },
    {
      name: 'flags',
      dataType: 'BIT',
      isBooleanAlias: false,
      isNullable: true,
      isPrimaryKey: false,
      isUniqueKey: false,
      hasDefault: false,
      columnDefault: null,
      isBinary: false,
      isAutoIncrement: false,
    },
    {
      name: 'label',
      dataType: 'VARCHAR',
      isBooleanAlias: false,
      isNullable: true,
      isPrimaryKey: false,
      isUniqueKey: false,
      hasDefault: false,
      columnDefault: null,
      isBinary: false,
      isAutoIncrement: false,
    },
  ],
  rows: [
    [1, 1, 255, 'All flags on'],
    [2, 0, 0, 'All flags off'],
    [3, 1, 42, 'Some flags'],
    [4, 0, null, 'Null flags'],
  ],
  currentPage: 1,
  pageSize: 1000,
  primaryKey: {
    keyColumns: ['id'],
    hasAutoIncrement: true,
    isUniqueKeyFallback: false,
  },
  executionTimeMs: 5,
}
