import type { PlaywrightListColumn, PlaywrightTableDataResult } from './types'

export const DEFAULT_TABLE_LIST_COLUMNS: PlaywrightListColumn[] = [
  {
    name: 'id',
    dataType: 'bigint',
    nullable: false,
    columnKey: 'PRI',
    defaultValue: null,
    extra: 'auto_increment',
    ordinalPosition: 1,
  },
]

export const DEFAULT_TABLE_DATA: PlaywrightTableDataResult = {
  columns: [
    {
      name: 'id',
      dataType: 'INT',
      isBooleanAlias: false,
      isNullable: false,
      isPrimaryKey: true,
      isUniqueKey: false,
      hasDefault: false,
      columnDefault: null,
      isBinary: false,
      isAutoIncrement: true,
    },
    {
      name: 'name',
      dataType: 'VARCHAR',
      isBooleanAlias: false,
      isNullable: true,
      isPrimaryKey: false,
      isUniqueKey: false,
      hasDefault: false,
      columnDefault: null,
      isBinary: false,
      isAutoIncrement: false,
    },
    {
      name: 'email',
      dataType: 'VARCHAR',
      isBooleanAlias: false,
      isNullable: true,
      isPrimaryKey: false,
      isUniqueKey: false,
      hasDefault: false,
      columnDefault: null,
      isBinary: false,
      isAutoIncrement: false,
    },
    {
      name: 'status',
      dataType: 'ENUM',
      isBooleanAlias: false,
      enumValues: ['active', 'inactive'],
      isNullable: false,
      isPrimaryKey: false,
      isUniqueKey: false,
      hasDefault: true,
      columnDefault: 'active',
      isBinary: false,
      isAutoIncrement: false,
    },
    {
      name: 'created_at',
      dataType: 'DATETIME',
      isBooleanAlias: false,
      isNullable: true,
      isPrimaryKey: false,
      isUniqueKey: false,
      hasDefault: false,
      columnDefault: null,
      isBinary: false,
      isAutoIncrement: false,
    },
    {
      name: 'updated_at',
      dataType: 'TIMESTAMP',
      isBooleanAlias: false,
      isNullable: true,
      isPrimaryKey: false,
      isUniqueKey: false,
      hasDefault: false,
      columnDefault: null,
      isBinary: false,
      isAutoIncrement: false,
    },
    {
      name: 'birth_date',
      dataType: 'DATE',
      isBooleanAlias: false,
      isNullable: true,
      isPrimaryKey: false,
      isUniqueKey: false,
      hasDefault: false,
      columnDefault: null,
      isBinary: false,
      isAutoIncrement: false,
    },
    {
      name: 'login_time',
      dataType: 'TIME',
      isBooleanAlias: false,
      isNullable: true,
      isPrimaryKey: false,
      isUniqueKey: false,
      hasDefault: false,
      columnDefault: null,
      isBinary: false,
      isAutoIncrement: false,
    },
  ],
  rows: [
    [
      1001,
      'Julian Thorne',
      'j.thorne@example.com',
      'active',
      '2023-11-24 14:30:00',
      '2023-11-24 14:30:00',
      '1990-05-15',
      '09:30:00',
    ],
    [
      1002,
      'Elena Vasquez',
      null,
      'active',
      '2023-12-01 09:00:00',
      '2023-12-01 09:00:00',
      '1985-08-22',
      '14:15:00',
    ],
    [
      1003,
      'Marcus Chen',
      'marcus@db.net',
      'inactive',
      '2024-01-15 16:45:00',
      '2024-01-15 16:45:00',
      null,
      '08:00:00',
    ],
    [
      1004,
      'Sarah Park',
      'sarah@dev.co',
      'active',
      null,
      '2024-02-20 11:30:00',
      '1992-03-10',
      null,
    ],
  ],
  currentPage: 1,
  pageSize: 1000,
  primaryKey: {
    keyColumns: ['id'],
    hasAutoIncrement: true,
    isUniqueKeyFallback: false,
  },
  executionTimeMs: 42,
}
